### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by Kashishca** [09aryan/AlmaBase#1]
![io](https://github.com/09aryan/AlmaBase/assets/99637603/4df39807-ca7d-45ef-80f4-79f7d8c790f2)
![m8](https://github.com/09aryan/AlmaBase/assets/99637603/94947f8b-d1f3-492a-a788-1b57148c68c6)
![image5](https://github.com/09aryan/AlmaBase/assets/99637603/5d02219e-c683-40d7-8406-e48d55ebfbee)
![image6](https://github.com/09aryan/AlmaBase/assets/99637603/33d2f42f-8c65-485b-a6c0-f61926820771)
![image1](https://github.com/09aryan/AlmaBase/assets/99637603/78b6f9b9-034a-42cd-bb8a-ebf2616f1204)
![mage3](https://github.com/09aryan/AlmaBase/assets/99637603/7be5f7ff-d75f-449f-82f1-ca2fee3d1048)
![am7](https://github.com/09aryan/AlmaBase/assets/99637603/ed72b79c-cab3-4db2-bd6d-f0888df5a4c6)
![y](https://github.com/09aryan/AlmaBase/assets/99637603/49cbc0bf-ee6f-486b-91ab-8356585d9063)

**Comment by 09aryan** [comment]
issue solved
